### ISSUE TITLE
Merge 2 cloud optimized geotiff (cog) using leaflet

### ISSUE THREAD

**Issue by abdul-imran** [GeoTIFF/georaster-layer-for-leaflet-example#15]
Hi,

My task is to load 2 geotiffs on the same map. I can load these raters fine by making use of the below snippet.

```
var cog1-url = "<s3-cog-1-url>";
var cog2-url= "<s3-cog-2-url>";

// Layer 1
   parseGeoraster().then(georaster => {
      var layer_1 = new GeoRasterLayer({
        georaster: georaster,
        opacity: 0.55,
        pixelValuesToColorFn: values => (values[0] == 2 || values[0] == 3 || values[0] == 4) ? '#66c4c4' :
          (values[0] == 0 || values[0] == 1) ? '#009c9c' : 'transparent',
        resolution: 128
      });

       layer_1.addTo(map);
    });

// Layer 2
   parseGeoraster().then(georaster => {
      var layer_2 = new GeoRasterLayer({
        georaster: georaster,
        opacity: 0.55,
        pixelValuesToColorFn: values => (values[0] == 2 || values[0] == 3 || values[0] == 4) ? '#FEF7BA' :
          (values[0] == 0 || values[0] == 1) ? '#FFE600' : 'transparent',
        resolution: 128
      });

       layer_2.addTo(map);
    });
```

I would like to add layer 2 on top of layer 1. This means when there is color overlap in a area, I'd like to display the color that corresponds to layer 2. 
But actually the colors overlap resulting in a different shade. I've tried using zindex for layers & also played with the opacity values, but that doesn't help,

We can achieve this by merging the layers in GeoServer, but I'd like to know if this can be done using Leaflet alone? Or may be by making use of some plugins?

Thanks.

**Expected Layer after grouping**
![Expected](https://user-images.githubusercontent.com/93587623/196892907-dd074699-5c84-4074-9f6a-e1c8d02480fb.PNG)

**Actual Layer after grouping**
![Result](https://user-images.githubusercontent.com/93587623/196892945-cc14f7f8-0733-4964-98e7-9c043886cb05.PNG)

**Comment by DanielJDufour** [comment]
Hi, @abdul-imran .  That's a very interesting question indeed!  I think what you want might be achieved by using Leaflet's Custom Panes: https://leafletjs.com/examples/map-panes/.  I haven't done it before, so it's just a guess.  I think you could set each layer's opacity to 1 (no opacity).  You could then set an opacity for the pane as a whole.  This might require you to manually set the css of the pane element.  Unfortunately, I have limited time at the moment, so I won't be able to be much more help.  Let me know how it goes!

**Comment by abdul-imran** [comment]
Thank you @DanielJDufour .
Unfortunately, this too doesn't work. The behavior is same as before. This is mainly because the colors from 2 layers overlap.
These are the changes I made. I have learnt about map panes now.

```
    map.createPane('layer-1');
    map.createPane('layer-2');

    map.getPane('layer-1').style.zIndex = 200;
    map.getPane('layer-1').style.opacity = 0.55;
    
    map.getPane('layer-2').style.zIndex = 201000;
    map.getPane('layer-2').style.opacity = 0.55;
    
      layer_1 = new GeoRasterLayer({
        georaster: georaster,
        opacity: 1,
        pane: 'layer-1',
        .
        . 

      layer_2 = new GeoRasterLayer({
        georaster: georaster,
        opacity: 1,
        pane: 'layer-2',
        .
        .
```

**Comment by DanielJDufour** [comment]
What if both layers use the same pane?

**Comment by abdul-imran** [comment]
Thank you @DanielJDufour. Your solution works great for me.

**Comment by DanielJDufour** [comment]
Glad it helped.  I'm going to close this issue, but please feel free to open an issue again if you find one.  Thank you.
