### ISSUE TITLE
Loading COGs from local disk

### ISSUE THREAD

**Issue by maawoo** [GeoTIFF/georaster-layer-for-leaflet-example#6]
Hi Daniel! 
I'm working on a simple web app using Flask for a university project and right now I'm trying to figure out how to load a COG that I have stored locally.
Loading the file as described in 'load-file.html' worked pretty well, so I guess that's a good start and I also saw that you load a local file in 'main.js'. Based on this, I tried the following:

```
// initalize leaflet map
var map = L.map('map').setView([0, 0], 5);

// add OpenStreetMap basemap
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var file = "file:///D:/grass/output/cog_4326/test_cog.tif";

fetch(file)
  .then(response => response.arrayBuffer())
  .then(arrayBuffer => {
    parse_georaster(arrayBuffer).then(georaster => {
      console.log("georaster:", georaster);

      var layer = new GeoRasterLayer({
          georaster: georaster,
          opacity: 0.8,
          resolution: 256
      });

      layer.addTo(map);

      map.fitBounds(layer.getBounds());

  });
});
```
Which results in:
`Security Error: Content at http://127.0.0.1:5000/map may not load or link to file:///D:/grass/output/cog_4326/test_cog.tif. TypeError: NetworkError when attempting to fetch resource.`

And:
```
// initalize leaflet map
var map = L.map('map').setView([0, 0], 5);

// add OpenStreetMap basemap
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var file = "file:///D:/grass/output/cog_4326/test_cog.tif";

var reader = new FileReader();
reader.readAsArrayBuffer(file);
reader.onloadend = function() {
    var arrayBuffer = reader.result;
    parseGeoraster(arrayBuffer).then(georaster => {

    var layer = new GeoRasterLayer({
        georaster: georaster,
        opacity: 0.8,
        resolution: 256
    });

    layer.addTo(map);

    map.fitBounds(layer.getBounds());

  });
};
```
Which results in `TypeError: FileReader.readAsArrayBuffer: Argument 1 is not an object.`

As you probably have guessed by now... I'm not very experienced in Javascript (and I'm not planning to become an expert), so I hope that I'm just making a simple stupid mistake. 
Your help is very much appreciated if you find the time! In the meantime I'll continue researching on my own. 

Cheers, Marco

**Comment by maawoo** [comment]
Found a solution and now it works like a charm!

Add a new Flask route using `send_from_directory` : 

```
@app.route('/serve/<path:filename>')
def serve_file(filename):
    return send_from_directory('D:/your/directory',
                               filename,
                               as_attachment=True)
```

And using the first example from above, just exchange the `var file = ...` line to the following:

```
var file = "{{ url_for('serve_file', filename='your-raster.tif') }}";
```

**Comment by DanielJDufour** [comment]
Great job! Thanks for sharing. This will be helpful to others you run into the same challenge!
